### PR TITLE
[FSTORE-748] Flying duck: Monitoring

### PR DESCRIPTION
**Pull request by bubriks**

### CODE REVIEW

**Comment by bubriks** [comment]
Kazam_screenshot_00015

**Review by SirOibaf — CHANGES_REQUESTED** [review]
@tdoehmen / @bubriks - can we show pending request and memory utilization of the python service?

also @bubriks, you usually don't care about the absolute number of requests, you usually care about the rate of requests per given time. Can you make the dashboard show the rate instead of the absolute amount?

**Comment by bubriks** [comment]
image

**Comment by bubriks** [comment]
image

**Comment by bubriks** [comment]
now it looks like this
image

**Comment by bubriks** [comment]
Now it looks like this:
image

**Comment by bubriks** [comment]
image

**Comment by bubriks** [comment]
image

**Comment by bubriks** [comment]
image

**Comment by tdoehmen** [comment]
@SirOibaf we merge monitoring into flyingduck (https://github.com/logicalclocks/flyingduck/pull/29), so this can be merged now as well.

**Comment by SirOibaf** [comment]
@bubriks / @tdoehmen - In the screenshots I don't see a way of selecting which flyingduck instance to see the metrics for. If you check the other dashboards we have a drop down menu on the top left to select the IP of the node.

Can you add the same in the flyingduck dashboard as well?

**Comment by bubriks** [comment]
image
image
@SirOibaf should be done

**Review by SirOibaf — APPROVED** [review]

**Pull request merged**
